### PR TITLE
Removed stuff now handled by spatie/laravel-json-api-paginate

### PR DESCRIPTION
**Pull request by clarkwinkelmann**
The `paginator->append` stuff is handled by Spatie (everything except the page number is copied to the paginator) and doing the `limit` and `offset` stuff ourself probably interferes with higher page numbers, no ?

Please check this before merging.

### CODE REVIEW

**Comment by luceos** [comment]
You can verify this works properly by looking at the homepage, it should only show 6 items (favorite and top downloaded). If that is still okay, merge at will.

**Comment by clarkwinkelmann** [comment]
I'll check that Thursday :wink:

**Comment by luceos** [comment]
@clarkwinkelmann please merge or close and delete branch.

**Comment by clarkwinkelmann** [comment]
@luceos totally forgot about this PR. Will do !

**Comment by clarkwinkelmann** [comment]
I finally did it @luceos . I added tests to make sure everything removed does not impact the good working.

So I can finally confirm, all the calls I removed were redundant and weren't needed anymore :innocent: 

Do you mind taking a look at the way I added the tests and confirm it's done in a style we agree on ? Then you can merge directly :wink:

**Pull request merged**
